force-app/main/default/objects/Property__c/fields/Age_Of_Construction__c.field-meta.xml
<CustomField>
    <fullName>Age_Of_Construction__c</fullName>
    <formula>YEAR(TODAY())  -  YEAR(Property_completion_date__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Age Of Construction</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Balconies__c.field-meta.xml
<CustomField>
    <fullName>Balconies__c</fullName>
    <label>Balconies</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Current_Owner__c.field-meta.xml
<CustomField>
    <fullName>Current_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Current Owner</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Furnished_Status__c.field-meta.xml
<CustomField>
    <fullName>Furnished_Status__c</fullName>
    <label>Furnished Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Furnished_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property__c/fields/Possession_Status__c.field-meta.xml
<CustomField>
    <fullName>Possession_Status__c</fullName>
    <label>Possession Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Possession_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property__c/fields/Total_Carpet_Area__c.field-meta.xml
<CustomField>
    <fullName>Total_Carpet_Area__c</fullName>
    <formula>TEXT(Carpet_Area__c)  &amp; &quot; &quot; &amp;   TEXT(carpetAreaUnit__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Carpet Area</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Type__c</fullName>
    <label>Transaction Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Transaction_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property_Media__c/Property_Media__c.object-meta.xml
<CustomObject>
    <label>Property Media</label>
    <nameField>
        <displayFormat>PM-{0000}</displayFormat>
        <label>Property Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Property Medias</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Property_Media__c/fields/ExternalLink__c.field-meta.xml
<CustomField>
    <fullName>ExternalLink__c</fullName>
    <label>External Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Property_Media__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Property Medias</relationshipLabel>
    <relationshipName>Property_Medias</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Property_Media__c/fields/Tags__c.field-meta.xml
<CustomField>
    <fullName>Tags__c</fullName>
    <label>Tags</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Exterior View</fullName>
            </value>
            <value>
                <fullName>Living Room</fullName>
            </value>
            <value>
                <fullName>Bedrooms</fullName>
            </value>
            <value>
                <fullName>Bathrooms</fullName>
            </value>
            <value>
                <fullName>Kitchen</fullName>
            </value>
            <value>
                <fullName>Site View</fullName>
            </value>
            <value>
                <fullName>Floor Plan</fullName>
            </value>
            <value>
                <fullName>Master Plan</fullName>
            </value>
            <value>
                <fullName>Location Map</fullName>
            </value>
            <value>
                <fullName>Common Area</fullName>
            </value>
            <value>
                <fullName>Washrooms</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ESX_PropertyDetailsController.cls
public without sharing class ESX_PropertyDetailsController {

    @AuraEnabled
    public static PropertyWrapper getPropertyInformation(Id propertyId){
        try {
            List<Property__c> property = [SELECT Id,Name,Street__c,State__c,City__c,Landmark__c,Country__c,Locality__c,Current_Owner__r.Name,Number_of_Bedrooms__c,Number_of_Bathrooms__c,Number_of_Floors__c,Balconies__c,Furnished_Status__c,Price__c,Total_Carpet_Area__c,Transaction_Type__c,Possession_Status__c,Age_Of_Construction__c FROM Property__c WHERE Id =:propertyId];
            List<String> propertyMedias = new List<String>();
            List<Property_Media__c> mediaRecords = new List<Property_Media__c>();
            mediaRecords = [SELECT Property__c, ExternalLink__c,Tags__c FROM Property_Media__c WHERE Property__c =:propertyId];
            // if(mediaRecords.size()>0){
            //     for(Property_Media__c media: mediaRecords){
            //         propertyMedias.add(media.ExternalLink__c);
            //     }
            // }
            PropertyWrapper propertyInfo = new PropertyWrapper();

            propertyInfo.property = property[0];
            propertyInfo.mediaLinks = mediaRecords;
            return propertyInfo;
        } catch (Exception e) {
            return null;
        }
        
    }

    public class PropertyWrapper {
        @AuraEnabled
        public Property__c property { get; set; }
        
        @AuraEnabled
        public List<Property_Media__c> mediaLinks { get; set; }
    }
}