force-app/main/default/objects/Property__c/fields/Brokerage__c.field-meta.xml
<CustomField>
    <fullName>Brokerage__c</fullName>
    <label>Brokerage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brokerage</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property__c/fields/carpetAreaUnit__c.field-meta.xml
<CustomField>
    <fullName>carpetAreaUnit__c</fullName>
    <label>carpetAreaUnit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>AreaUnit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property__c/fields/coveredAreaUnit__c.field-meta.xml
<CustomField>
    <fullName>coveredAreaUnit__c</fullName>
    <label>coveredAreaUnit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>AreaUnit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property__c/fields/Floor_No__c.field-meta.xml
<CustomField>
    <fullName>Floor_No__c</fullName>
    <label>Floor No</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Floor_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property__c/fields/Furnished_Status__c.field-meta.xml
<CustomField>
    <fullName>Furnished_Status__c</fullName>
    <label>Furnished Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Furnished_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property__c/fields/Indoor_Facilities__c.field-meta.xml
<CustomField>
    <fullName>Indoor_Facilities__c</fullName>
    <label>Indoor Facilities</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Indoor_Facilities</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property__c/fields/Outdoor_Facilities__c.field-meta.xml
<CustomField>
    <fullName>Outdoor_Facilities__c</fullName>
    <label>Outdoor Facilities</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Outdoor_Facilities</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property__c/fields/Possession_Status__c.field-meta.xml
<CustomField>
    <fullName>Possession_Status__c</fullName>
    <label>Possession Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Possession_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property__c/fields/Price_Includes__c.field-meta.xml
<CustomField>
    <fullName>Price_Includes__c</fullName>
    <label>Price Includes</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Price_Includes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property__c/fields/Property_Type__c.field-meta.xml
<CustomField>
    <fullName>Property_Type__c</fullName>
    <label>Property Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Property_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property__c/fields/Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Type__c</fullName>
    <label>Transaction Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Transaction_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/ESX_PropertyInsertFormController.cls
public with sharing class ESX_PropertyInsertFormController {
    public class PicklistWrapper {
        @AuraEnabled public List<String> propertyTypes { get; set; }
        @AuraEnabled public List<String> floorNumbers { get; set; }
        @AuraEnabled public List<String> furnishedStatuses { get; set; }
        @AuraEnabled public List<String> transactionTypes { get; set; }
        @AuraEnabled public List<String> priceIncludes { get; set; }
        @AuraEnabled public List<String> possessionStatus { get; set; }
        @AuraEnabled public List<String> indoorFacilities { get; set; }
        @AuraEnabled public List<String> outdoorFacilities { get; set; }
        @AuraEnabled public List<String> brokerages { get; set; }
        @AuraEnabled public List<String> carpetareaUnits { get; set; }
        @AuraEnabled public List<String> coveredareaUnits { get; set; }




    }

    @AuraEnabled(cacheable=true)
    public static PicklistWrapper getAllPicklistValues() {
        PicklistWrapper wrapper = new PicklistWrapper();
        wrapper.propertyTypes = getPicklistValues('Property_Type__c');
        wrapper.floorNumbers = getPicklistValues('Floor_No__c');
        wrapper.furnishedStatuses = getPicklistValues('Furnished_Status__c');
        wrapper.transactionTypes = getPicklistValues('Transaction_Type__c');
        wrapper.priceIncludes = getPicklistValues('Price_Includes__c');
        wrapper.possessionStatus = getPicklistValues('Possession_Status__c');
        wrapper.indoorFacilities = getPicklistValues('Indoor_Facilities__c');
        wrapper.outdoorFacilities = getPicklistValues('Outdoor_Facilities__c');
        wrapper.brokerages = getPicklistValues('Brokerage__c');
        wrapper.carpetareaUnits = getPicklistValues('carpetAreaUnit__c');
        wrapper.coveredareaUnits = getPicklistValues('coveredAreaUnit__c');



        return wrapper;
    }

    private static List<String> getPicklistValues(String fieldName) {
        List<String> picklistValues = new List<String>();
        Schema.DescribeFieldResult fieldResult = Schema.SObjectType.Property__c.fields.getMap().get(fieldName).getDescribe();
        List<Schema.PicklistEntry> picklistEntries = fieldResult.getPicklistValues();

        for (Schema.PicklistEntry entry : picklistEntries) {
            picklistValues.add(entry.getLabel());
        }

        return picklistValues;
    }
}