force-app/main/default/objects/Property__c/fields/Property_Status__c.field-meta.xml
<CustomField>
    <fullName>Property_Status__c</fullName>
    <label>Property Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Property_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property__c/fields/Total_Covered_Area__c.field-meta.xml
<CustomField>
    <fullName>Total_Covered_Area__c</fullName>
    <formula>TEXT(Covered_Area__c )  &amp; &quot; &quot;  &amp;  TEXT( coveredAreaUnit__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Covered Area</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property_Media__c/Property_Media__c.object-meta.xml
<CustomObject>
    <label>Property Media</label>
    <nameField>
        <displayFormat>PM-{0000}</displayFormat>
        <label>Property Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Property Medias</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Property_Media__c/fields/ExternalLink__c.field-meta.xml
<CustomField>
    <fullName>ExternalLink__c</fullName>
    <label>External Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Property_Media__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Property Medias</relationshipLabel>
    <relationshipName>Property_Medias</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ESX_LatestPropertyController.cls
public with sharing class ESX_LatestPropertyController {
    @AuraEnabled(cacheable=true)
    public static List<PropertyWrapper> getPropertyListing(){
        List<Property__c> properties = [SELECT Id, Name, Number_of_Bedrooms__c, Number_of_Bathrooms__c, Landmark__c, City__c, Price__c, Total_Covered_Area__c, Property_Status__c	 
                                         FROM Property__c WHERE Property_Status__c = 'For Sell' OR Property_Status__c = 'For Rent'];

        List<PropertyWrapper> propertyList = new List<PropertyWrapper>();

        for(Property__c prop : properties) {
            PropertyWrapper pw = new PropertyWrapper();
            pw.property = prop;
            pw.mediaLinks = getExternalLinks(prop.Id);
            propertyList.add(pw);
        }
        
        return propertyList;
    }

    @AuraEnabled(cacheable=true)
    public static List<String> getExternalLinks(Id propertyId) {
        List<String> externalLinks = new List<String>();
        List<Property_Media__c> mediaRecords = [SELECT ExternalLink__c FROM Property_Media__c WHERE Property__c = :propertyId limit 1];
        for(Property_Media__c media : mediaRecords) {
            externalLinks.add(media.ExternalLink__c);
        }
        return externalLinks;   
    }

    public class PropertyWrapper {
        @AuraEnabled
        public Property__c property { get; set; }
        
        @AuraEnabled
        public List<String> mediaLinks { get; set; }
    }

    @AuraEnabled(cacheable=true)
    public static List<PropertyWrapper> getPropertiesByStatus(String status) {
        String query = 'SELECT Id, Name, Number_of_Bedrooms__c, Number_of_Bathrooms__c, Landmark__c, City__c, Price__c, Total_Covered_Area__c, Property_Status__c FROM Property__c';
        
        if (status == 'sell') {
            query += ' WHERE Property_Status__c = \'For Sell\'';
        } else if (status == 'rent') {
            query += ' WHERE Property_Status__c = \'For Rent\'';
        }
        
        List<Property__c> properties = Database.query(query);
        List<PropertyWrapper> propertyList = new List<PropertyWrapper>();

        for(Property__c prop : properties) {
            PropertyWrapper pw = new PropertyWrapper();
            pw.property = prop;
            pw.mediaLinks = getExternalLinks(prop.Id);
            propertyList.add(pw);
        }
        
        return propertyList;
    }
}