force-app/main/default/objects/Listing__c/Listing__c.object-meta.xml
<CustomObject>
    <label>Listing</label>
    <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>Listing Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Listings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Listing__c/fields/Listing_Date__c.field-meta.xml
<CustomField>
    <fullName>Listing_Date__c</fullName>
    <label>Listing Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Listing__c/fields/Listing_Description__c.field-meta.xml
<CustomField>
    <fullName>Listing_Description__c</fullName>
    <label>Listing Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Listing__c/fields/Listing_Price__c.field-meta.xml
<CustomField>
    <fullName>Listing_Price__c</fullName>
    <formula>Property__r.Price__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Listing Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Listing__c/fields/Listing_Status__c.field-meta.xml
<CustomField>
    <fullName>Listing_Status__c</fullName>
    <label>Listing Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Listing__c/fields/Listing_Type__c.field-meta.xml
<CustomField>
    <fullName>Listing_Type__c</fullName>
    <formula>TEXT(Property__r.Property_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Listing Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Listing__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Listings</relationshipLabel>
    <relationshipName>Listings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Property_Media__c/Property_Media__c.object-meta.xml
<CustomObject>
    <label>Property Media</label>
    <nameField>
        <displayFormat>PM-{0000}</displayFormat>
        <label>Property Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Property Medias</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Property_Media__c/fields/ExternalLink__c.field-meta.xml
<CustomField>
    <fullName>ExternalLink__c</fullName>
    <label>External Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Property_Media__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Property Medias</relationshipLabel>
    <relationshipName>Property_Medias</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ESX_PropertyDataTableController.cls
public without sharing class ESX_PropertyDataTableController {
    public ESX_PropertyDataTableController() {

    }

    @AuraEnabled(cacheable=true)
    public static List<Property__c> getListingData(Integer listingSize){
        try {
            List<Property__c> propertyData = new List<Property__c>();
            Map<Id,Id> propertyId = new Map<Id,Id>();
            List<Listing__c> listingData = new List<Listing__c>();
            List<Property_Media__c> propertyMediaData = new List<Property_Media__c>();

            // listingData = [SELECT Id, Name,Property__c,Listing_Type__c,Listing_Status__c, Listing_Price__c,Listing_Description__c,Listing_Date__c FROM     ORDER BY CreatedDate DESC LIMIT 50000 OFFSET : listingSize];

            // for (Listing__c lis : listingData) {
            //     propertyId.put(lis.Id,lis.Property__c);
            // }

            // propertyMediaData = [SELECT Id,ExternalLink__c,Property__c FROM Property_Media__c WHERE Property__c IN : propertyId.values()];   



            propertyData = [SELECT ID,(SELECT ID, Name,Property__c,Listing_Type__c,Listing_Status__c, Listing_Price__c,Listing_Description__c,Listing_Date__c FROM  Listings__r ORDER BY CreatedDate DESC LIMIT 1),
                                    (SELECT Id,ExternalLink__c,Property__c FROM Property_Medias__r ORDER BY CreatedDate DESC LIMIT 1) FROM Property__c ORDER BY CreatedDate DESC LIMIT 50000 ];

                                    System.debug('propertyData--->'+propertyData);


            return propertyData;
            
        } catch (Exception e) {
           System.debug('error--->'+ e.getMessage() + ' '  + e.getLineNumber());
           return null;
        }
    }


    // public class propertyDetail {
    //     @AuraEnabled
    //     public Integer index {get; set;}
    //     @AuraEnabled
    //     public string name {get; set;}
    //     @AuraEnabled
    //     public Id contactId {get; set;}
    //     @AuraEnabled
    //     public String error {get; set;}
    // }
}